alias sp='cd /proj/i4sp2/is76ifoc/trunk'
alias ..='cd ..'
alias tmp='cd /proj/ciptmp/is76ifoc'
alias hacklab='sudo openvpn --config /etc/openvpn/client-hackinglab.conf'
alias hack='cd ~/Dropbox/Uni/WS_17-18/HackPra/blatt6/a3/'
